INSERT INTO PAYS (id, PAYS) VALUES (1, 'France');
INSERT INTO PAYS (id, PAYS) VALUES (2, 'USA');
INSERT INTO PAYS (id, PAYS) VALUES (3, 'Brazil');
INSERT INTO PAYS (id, PAYS) VALUES (4, 'Italy');
INSERT INTO PAYS (id, PAYS) VALUES (5, 'Canada');